name: livelogs-release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    name: livelogs-release
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check linting
          uses: golangci/golangci-lint-action@v4
          with:
            version: v1.54
            args: -v -E gofmt -E gci --timeout 5m

      - name: Check commit details
        id: commit
        run: |
          echo "version=$(go run version/getVersion.go)" >> "$GITHUB_ENV"
          echo "changelog=$(git log --pretty='- %s')" >> "$GITHUB_ENV"

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ env.version }}
          message: ${{ env.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Asset
        run: |
          make compressed-builds

      - name: Generate Asset SHA256
        id: sha256
        run: |
          echo "darwin_amd64=$(shasum -a 256 bin/livelogs_darwin_amd64.tar.gz | cut -d' ' -f1)" >> "$GITHUB_ENV"
          echo "darwin_arm64=$(shasum -a 256 bin/livelogs_darwin_arm64.tar.gz | cut -d' ' -f1)" >> "$GITHUB_ENV"
          echo "linux_amd64=$(shasum -a 256 bin/livelogs_linux_amd64.tar.gz | cut -d' ' -f1)" >> "$GITHUB_ENV"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ env.version }}
          tag: ${{ env.version }}
          artifacts: "bin/*.tar.gz"
          body: |
            ### Changelog:
            ${{ env.changelog }}
            ---
            ### Assets

            #### Darwin AMD64
            - Asset Url: https://github.com/dream-sports-labs/livelogs/releases/download/${{ env.version }}/livelogs_darwin_amd64.tar.gz
            - SHA Checksum: `${{ env.darwin_amd64 }}`

            #### Darwin ARM64
            - Asset Url: https://github.com/dream-sports-labs/livelogs/releases/download/${{ env.version }}/livelogs_darwin_arm64.tar.gz
            - SHA Checksum: `${{ env.darwin_arm64 }}`

            #### Linux AMD64
            - Asset Url: https://github.com/dream-sports-labs/livelogs/releases/download/${{ env.version }}/livelogs_linux_amd64.tar.gz
            - SHA Checksum: `${{ env.linux_amd64 }}`

          token: ${{ secrets.GITHUB_TOKEN }}
